### ISSUE TITLE
i found a cockroach

### ISSUE THREAD

**Issue by Sweattypalms** [Skullians/ferrumc#1]
### Describe the Bug

dark orange, brown type shell, long whiskeys, and should be able to survive a nuclear blast

### To Reproduce

uhm 😳

### Expected Behaviour

i dont konw? like move around

### Screenshots / Videos

![american-cockroach](https://github.com/user-attachments/assets/e77310db-c401-4865-a110-9e881fedb539)

### FerrumC Version

i dont know like 0.1, its not like y'all update it anyways 💀💀

### Rust Version

1.82 i think

### Server Logs

[ferrumc] i had a dream "martin luther king"

### Additional Context

im sweattypalms

### Is there an existing issue for this?

- [X] I have searched current existing issues before creating this.
- [ ] I checked all the boxes without reading them
- [X] I have provided all necessary and relevant details, including logs, reproduction steps, etc.

**Comment by Skullians** [comment]
bad issue
